.TH HEXMIX 1 "OCTOBER 2015"
.SH NAME
hexmix \- Color mixing tool
.SH SYNOPSIS
.B hexmix
.I color1 color2
.B [--amount
.I %_of_color2
.B ]
.SH DESCRIPTION
Hexmix is a commandline utility to mix hexadecimal color codes.
.SH OPTIONS
.IP "-h"
Display help
.IP "-v"
Display version and author information
.IP "-a"
Amount of color2 to add to color1 from 0 to 1 inclusive [default: 0.5]
.SH AUTHOR
Weston Belk <contact@westonbelk.com>